name: PR Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add labels
        uses: actions/github-script@v7
        with:
          script: |
            const { data: files } = await github.rest.pulls.listFiles({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            const hasCode = files.some(file => file.filename.endsWith('.js') || file.filename.endsWith('.ts'));
            const hasTests = files.some(file => file.filename.includes('test') || file.filename.includes('spec'));
            const labels = [];
            if (hasCode) labels.push('code-change');
            if (hasTests) labels.push('tests');
            if (labels.length > 0) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels
              });
            }